### ISSUE TITLE
Fix link-checker check

### ISSUE THREAD

**Issue by quadratz** [grammyjs/website#910]
Somehow, the GitHub action for `Check Links` is not working correctly. The script always finishes without running the actual script.

**Comment by CikiMomogi** [comment]
Indeed, I'm referring to CI in pull requests. There is a new feature called merge queue. I think we can make it more clear by adding checks in the merge queue instead of pull request, so that pull requests can't be merged if CI fails. Here's an example video: https://www.youtube.com/watch?v=XEZMgohmtts

**Comment by dcdunkan** [comment]
Is this still in consideration? Otherwise, #1052 could close this issue, as it *basically\* fixes the link-checker task.

> so that pull requests can't be merged if CI fails

@quadratz If you meant that the CI job should fail if there is a broken link somewhere in the documentation, I wouldn't want that. Because only a small percent of links can be handled by us. The rest are handled and served by random providers and those could break at any time. I think that is why the job is set to run only on the `main` branch.
